### ISSUE TITLE
FCP v1.0.0 permission deniedpanic: failed to connect database

### ISSUE THREAD

**Issue by ThomasBlock** [swanchain/go-computing-provider#192]
FCP v1.0.0 not working for me:
what folders should i reset and what should i keep?

```
/usr/local/bin/computing-provider -v
computing-provider version 1.0.0+mainnet+git.a1fb5e0


computing-provider info
/home/user/go-computing-provider/internal/db/db.go:22
[error] failed to initialize database, got error unable to open database file: permission deniedpanic: failed to connect database

goroutine 1 [running]:
github.com/swanchain/go-computing-provider/internal/db.InitDb({0xc000014028?, 0x8?})
	/home/user/go-computing-provider/internal/db/db.go:30 +0x4d8
main.main.func1(0xc000136480)
	/home/user/go-computing-provider/cmd/computing-provider/main.go:75 +0x2f1
github.com/urfave/cli/v2.(*Command).Run(0xc0006a3ce0, 0xc000136480, {0xc00024a060, 0x2, 0x2})
	/home/user/go/pkg/mod/github.com/urfave/cli/v2@v2.27.4/command.go:216 +0x50e
github.com/urfave/cli/v2.(*App).RunContext(0xc0006d6400, {0x3c5e8c8, 0x529a680}, {0xc00024a060, 0x2, 0x2})
	/home/user/go/pkg/mod/github.com/urfave/cli/v2@v2.27.4/app.go:333 +0x5a5
github.com/urfave/cli/v2.(*App).Run(...)
	/home/user/go/pkg/mod/github.com/urfave/cli/v2@v2.27.4/app.go:307
main.main()
	/home/user/go-computing-provider/cmd/computing-provider/main.go:83 +0x372
```

**Comment by ThomasBlock** [comment]
solved: permission problems for CP_PATH
